kind: pipeline
name: default

steps:
- name: hello
  image: python:3-alpine
  commands:
    - pip3 install awscli
    - aws s3 ls s3://moxaics
  when:
    event:
      exclude:
        - promote

- name: hello2
  image: python:3-alpine
  commands:
    - echo "do something when deploy event"
    - env
  when:
    event: promote
    environment: production
