kind: pipeline
name: default

steps:
- name: hello
  image: python:3-alpine
  commands:
    - pip3 install awscli
    - echo test

- name: upload-to-stable
  image: alpine
  commands:
  - env
  when:
    event:
    - promote
