kind: pipeline
name: default

steps:
- name: hello
  image: python:3-alpine
  commands:
    - pip3 install awscli
    - aws s3 ls s3://moxaics
  when:
    event:
      exclude:
        - deployment

- name: hello2
  image: python:3-alpine
  commands:
    - echo "do something when deploy event"
  when:
    event: deployment
    environment: production
