kind: pipeline
name: default

steps:
- name: hello
  image: python:3-alpine
  commands:
    - apk add vim

- name: upload-to-stable
  image: alpine
  commands:
  - env
  when:
    event:
    - promote

- name: tag
  image: alpine
  commands:
  - env
  when:
    event:
    - tag
